### ISSUE TITLE
Either must be sealed

### ISSUE THREAD

**Issue by yarulan** [adelnizamutdinov/kotlin-either#1]
Either must be sealed, so that compiler can check match exhaustiveness and we don't write unnecessary else clauses.

**Comment by meoyawn** [comment]
Hey!

sorry for the time it took, I just noticed this issue :)

Thing is, I wanted `Left` and `Right` to be `data class`, and have equals, hashcode and toString
Kotlin does not support sealed data classes as of 1.0.2, so I went with `interface`

But the thing is - you don't want to match on your either every time anyway, so I included the fold function
It does the same thing, matches on left or right, but it also unboxes the values, and is checked by the compiler

**Comment by yaroslav-ulanovych** [comment]
Thanks for the explanation!

**Comment by meoyawn** [comment]
@yaroslav-ulanovych I guess one could implement this with `sealed class` and add the `equals` and other implementations by hand

Kotlin's ADT story is very messy at the moment

**Comment by meoyawn** [comment]
updated to sealed classes
